# 服务器配置
server:
  servlet:
    context-path: /api          # 应用上下文路径，所有请求都会加上这个前缀
    encoding:                   # 字符编码配置
      charset: UTF-8            # 字符集
      force: true              # 强制使用配置的字符集
      enabled: true            # 启用字符编码配置

# Spring基础配置
spring:
  application:
    name: risk-management       # 应用名称，用于服务注册和日志标识
  profiles:
    active: dev                # 激活的开发环境配置

# 数据源配置
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver  # SQL Server驱动类
    type: com.alibaba.druid.pool.DruidDataSource                     # 使用Druid连接池
    druid:
      # 连接池基础配置
      initial-size: 5          # 初始连接数，建议设置为5-10
      min-idle: 5              # 最小空闲连接数，建议与initial-size相同
      max-active: 20           # 最大活动连接数，建议设置为20-50
      max-wait: 60000          # 获取连接等待超时时间，单位毫秒
      
      # 连接池检测配置
      test-while-idle: true    # 空闲时检测连接是否有效
      time-between-eviction-runs-millis: 60000  # 检测间隔时间，单位毫秒
      min-evictable-idle-time-millis: 300000    # 最小空闲时间，单位毫秒
      max-evictable-idle-time-millis: 900000    # 最大空闲时间，单位毫秒
      
      # 连接验证配置
      validation-query: SELECT 1  # 验证连接是否有效的SQL
      test-on-borrow: false      # 获取连接时是否验证
      test-on-return: false      # 归还连接时是否验证
      
      # 连接池性能配置
      pool-prepared-statements: true  # 是否缓存PreparedStatement
      max-pool-prepared-statement-per-connection-size: 20  # 每个连接最大缓存数

      # Druid监控配置
      web-stat-filter:          # Web监控过滤器配置
        enabled: true           # 启用Web监控
        url-pattern: /*         # 监控的URL模式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"  # 排除的URL
        session-stat-enable: true  # 是否监控Session
        session-stat-max-count: 1000  # 最大Session数
        profile-enable: true    # 是否监控单个URL调用信息
        
      stat-view-servlet:        # 监控页面配置
        enabled: true           # 启用监控页面
        url-pattern: /druid/*   # 监控页面URL
        reset-enable: false     # 是否允许重置数据
        login-username: admin   # 监控页面登录用户名
        login-password: admin   # 监控页面登录密码
        allow: ""              # 允许访问的IP，空表示所有
        deny: ""               # 禁止访问的IP，空表示无
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"  # 排除的URL

      # Druid过滤器配置
      filter:                   # 过滤器配置
        stat:                   # 统计过滤器
          enabled: true         # 启用统计
          log-slow-sql: true    # 记录慢SQL
          slow-sql-millis: 2000 # 慢SQL阈值，单位毫秒
        wall:                   # 防火墙过滤器
          enabled: true         # 启用防火墙
          config:
            multi-statement-allow: true  # 允许执行多条SQL
        slf4j:                  # 日志过滤器
          enabled: true         # 启用日志
          statement-log-enabled: true    # 记录SQL执行日志
          statement-create-after-log-enabled: false  # 创建连接后是否记录日志
          statement-close-after-log-enabled: true    # 关闭连接后是否记录日志
          result-set-open-after-log-enabled: false   # 打开结果集后是否记录日志
          result-set-close-after-log-enabled: false  # 关闭结果集后是否记录日志

# Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  # 日期格式
    time-zone: GMT+8                  # 时区设置
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false  # 日期序列化格式，false表示使用ISO-8601格式

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml  # Mapper文件位置
  type-aliases-package: com.ocbc.les.modules.*.entity  # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名转换
    cache-enabled: true                 # 开启二级缓存
    lazy-loading-enabled: true          # 开启延迟加载
    multiple-result-sets-enabled: true  # 支持多结果集
    use-generated-keys: true            # 使用生成的主键
    default-statement-timeout: 30       # 默认超时时间，单位秒
    default-fetch-size: 100             # 默认获取记录数
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL日志输出
  global-config:
    db-config:
      logic-delete-field: delFlag  # 逻辑删除字段
      logic-delete-value: '1'      # 逻辑已删除值
      logic-not-delete-value: '0'  # 逻辑未删除值
      id-type: auto                # 主键类型
#      table-prefix: t_            # 表名前缀

# JWT配置
jwt:
  secret: ocbc_les_risk_management_jwt_secret_key_2025  # JWT密钥
  expiration: 36000        # 访问令牌过期时间，10小时（秒）
  issuer: ocbc-les-risk     # Token签发者
  refresh: 300     # Token刷新时间窗口，5分钟（秒）
  threshold: 0.8 #本地与Redis同步阈值,通过刷新时间计算

# Knife4j配置（API文档增强）
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    enable-version: false
    enable-reload-cache-parameter: true
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-request-cache: true
    enable-host: false
    enable-host-text: 
    enable-home-custom: false
    home-custom-path: 
    enable-search: true
    enable-footer: false
    enable-footer-custom: false
    footer-custom-content: 
    enable-dynamic-parameter: false
    enable-debug: true
    enable-open-api: true
    enable-group: true
  basic:
    enable: false
    username: admin
    password: 123456
  cors: false
  production: false
  security:
    - name: Bearer
      type: apiKey
      in: header
      description: 输入Bearer {token}格式的JWT认证信息

# SpringDoc配置（OpenAPI文档）
springdoc:
  api-docs:
    enabled: true                       # 启用API文档
    path: /v3/api-docs                  # API文档路径
  swagger-ui:
    path: /swagger-ui.html              # Swagger UI路径
    tags-sorter: alpha                  # 标签排序方式
    operations-sorter: order            # 操作排序方式
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ocbc.les.modules
  show-actuator: true
  packages-to-scan: com.ocbc.les
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# 日志配置
logging:
  level:
    root: debug                          # 根日志级别
    com.ocbc.les: debug                  # 应用日志级别
    org.springframework.web: debug       # Spring Web日志级别
    org.springframework.security: debug  # Spring Security日志级别
    org.mybatis: debug                   # MyBatis日志级别
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{userId}][%X{traceId}] [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{userId}][%X{traceId}] [%thread] %-5level %logger{36} - %msg%n"

# 事务管理配置
transaction:
  monitor:
    enabled: true  # 是否启用事务监控
  prefix:
    readonly:  # 只读事务方法前缀
      - get
      - query
      - find
      - list
      - count
      - exist
      - search
      - fetch
      - select
    required:  # 读写事务方法前缀
      - add
      - save
      - insert
      - update
      - modify
      - delete
      - remove
      - batch
      - create
      - import
      - export
      - submit
      - process
      - execute
    none:  # 无事务方法前缀，可根据需要自定义
      - noTx